tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface-container-high": "#eae6de",
                "primary": "#4a7c59",
                "on-primary-fixed": "#002110",
                "surface-variant": "#e4e0d8",
                "surface": "#faf6f0",
                "on-tertiary-fixed-variant": "#554020",
                "tertiary-fixed": "#f8e0a8",
                "inverse-on-surface": "#f5f0e8",
                "surface-bright": "#faf6f0",
                "on-secondary-fixed-variant": "#4a4538",
                "surface-tint": "#4a7c59",
                "on-surface": "#2e3230",
                "on-primary": "#ffffff",
                "surface-container": "#f0ece4",
                "on-primary-fixed-variant": "#2a6038",
                "on-secondary": "#ffffff",
                "inverse-surface": "#2e3230",
                "on-background": "#2e3230",
                "primary-container": "#78a886",
                "outline": "#74796e",
                "on-tertiary-fixed": "#221a05",
                "surface-dim": "#dbd7cf",
                "secondary": "#6b6358",
                "secondary-fixed": "#f0e8db",
                "error": "#b83230",
                "tertiary-fixed-dim": "#dcc48e",
                "on-tertiary-container": "#554020",
                "on-error-container": "#690005",
                "primary-fixed-dim": "#8ecf9e",
                "inverse-primary": "#8ecf9e",
                "outline-variant": "#c4c8bc",
                "on-error": "#ffffff",
                "tertiary": "#705c30",
                "primary-fixed": "#c8e8d0",
                "secondary-container": "#f0e8db",
                "on-tertiary": "#ffffff",
                "on-secondary-container": "#5e5548",
                "tertiary-container": "#c4a66a",
                "surface-container-lowest": "#ffffff",
                "secondary-fixed-dim": "#d4ccbf",
                "on-surface-variant": "#4a4e4a",
                "error-container": "#ffdad8",
                "surface-container-low": "#f5f1ea",
                "surface-container-highest": "#e4e0d8",
                "on-secondary-fixed": "#1e1a13",
                "on-primary-container": "#d8f0de",
                "background": "#faf6f0"
            },
            "borderRadius": {
                "DEFAULT": "0.5rem",
                "lg": "1rem",
                "xl": "1.5rem",
                "full": "9999px"
            },
            "spacing": {
                "2xl": "48px",
                "xl": "32px",
                "lg": "24px",
                "3xl": "64px",
                "md": "16px",
                "xs": "4px",
                "sm": "8px",
                "container-max": "1200px",
                "gutter": "24px"
            },
            "fontFamily": {
                "headline": ["Literata"],
                "display": ["Literata"],
                "body": ["Nunito Sans"],
                "label": ["Nunito Sans"],
                "label-sm": ["Nunito Sans"],
                "label-md": ["Nunito Sans"],
                "headline-sm": ["Literata"],
                "display-lg": ["Literata"],
                "mono-data": ["Nunito Sans"],
                "body-lg": ["Nunito Sans"],
                "body-md": ["Nunito Sans"],
                "headline-md": ["Literata"],
                "body-sm": ["Nunito Sans"],
                "headline-lg": ["Literata"]
            },
            "fontSize": {
                "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
                "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}],
                "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "mono-data": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
            }
        },
    },
}
